# Generated by Django 2.0 on 2020-04-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appcasestep',
            old_name='Appcse',
            new_name='Appcase',
        ),
    ]
